name: SeaMonkeys

on:
  # runs on pushes to the main branch
  push:
    branches: [main]
  # also runs inside pull requests that target the main branch
  pull_request:
    branches: [main]

jobs:
  build:
    # uses a Ubuntu Docker image (like a virtual machine)
    runs-on: ubuntu-latest

    steps:
    - name: Make envfile
      with:
        envkey_DEBUG: false
        envkey_REACT_APP_SERVER_URL: http://localhost:3010
        file_name: .env
        fail_on_empty: false
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
          node-version: "18.x"
          #cache: "npm"
      # install dependencies
    - run: npm i
      # run tests
    - run: npm run test 
